# fly.toml app configuration file generated for minitify on 2025-11-17T20:02:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minitify'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  SPRING_DATA_MONGODB_URI = 'mongodb://minitify_admin:dGguHuvNN6gTdJlL9Oa9lXK4G093or9AyUYlfxl5W0Y=@131.108.73.167:27018/minitify_db?authSource=admin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health_status]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 8080
    timeout = "10s"
    type = "http"
    [checks.health_status]
      Content-Type = "application/json"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
